const kaleidoscope = {
    name: 'Kaleidoscope',
    description: 'A budget app',
    skills: {
        'Agile Development': 'used',
        'Authentication': 'used',
        'Behavior-Driven Development': 'Used',
        'Chai': 'used',
        'Command Line': 'used',
        'CRUD Pattern': 'used',
        'Design Patterns': 'used',
        'Error Handling': 'used',
        'Express': 'used', 
        'Git': 'used',
        'GitHub': 'used',
        'Heroku': 'used',
        'Information Architecture': 'used',
        'JavaScript': 'used', 
        'Mocha': 'used',
        'Mongo Atlas': 'used',
        'MongoDB': 'used',
        'Mongoose': 'used',
        'MVC Pattern': 'used',
        'Node': 'used',
        'NPM': 'used',
        'Object-Oriented Programming': 'used',
        'React': 'used', 
        'Responsive Design': 'used',
        'REST Pattern': 'used',
        'Sass': 'used',
        'Test-Driven Development': 'used',
        'User Experience Design': 'used',
        'Version Control': 'used',
        'Visual Studio Code': 'used',
        'Wireframing': 'used'
    },
    type: 'app',
    host: 'Heroku',
    image: '/images/projects/kaleidoscope/main.png',
    deployedLink: 'https://kaleidoscope-budget.herokuapp.com',
    repositoryLink: 'https://github.com/jtreeves/budget-frontend',
    date: 'December 2020'
}

export default kaleidoscope