const kaleidoscope = {
    name: 'Kaleidoscope',
    description: 'A budget app',
    skills: [
        'Agile Development',
        'Authentication',
        'Behavior-Driven Development',
        'Chai',
        'Command Line',
        'CRUD Pattern',
        'Design Patterns',
        'Error Handling',
        'Express', 
        'Git',
        'GitHub',
        'Heroku',
        'Information Architecture',
        'JavaScript', 
        'Mocha',
        'Mongo Atlas',
        'MongoDB',
        'Mongoose',
        'MVC Pattern',
        'Node',
        'NPM',
        'Object-Oriented Programming',
        'React', 
        'Responsive Design',
        'REST Pattern',
        'Sass',
        'Test-Driven Development',
        'User Experience Design',
        'Version Control',
        'Visual Studio Code',
        'Wireframing'
    ],
    type: 'app',
    host: 'Heroku',
    image: '/images/projects/kaleidoscope/main.png',
    deployedLink: 'https://kaleidoscope-budget.herokuapp.com',
    repositoryLink: 'https://github.com/jtreeves/budget-frontend',
    date: 'December 2020'
}

export default kaleidoscope