const tiresias = {
    name: 'Tiresias',
    description: 'An app for generating regressions models',
    skills: {
        'APIs': 'used',
        'Authentication': 'Used',
        'Bootstrap': 'used',
        'Chai': 'used',
        'Command Line': 'used',
        'Computer Science': 'used',
        'Design Patterns': 'used',
        'Error Handling': 'used',
        'Express': 'used', 
        'Git': 'Lorem Ipsum dolor sit amet',
        'GitHub': 'used',
        'Heroku': 'used',
        'Information Architecture': 'used',
        'JavaScript': 'used', 
        'Mocha': 'used',
        'Mongo Atlas': 'used',
        'MongoDB': 'used',
        'Mongoose': 'used',
        'MVC Pattern': 'used',
        'Node': 'used',
        'NPM': 'used',
        'Object-Oriented Programming': 'used',
        'React': 'used',
        'User Experience Design': 'used',
        'Version Control': 'used',
        'Visual Studio Code': 'used',
        'Wireframing': 'used'
    },
    type: 'app',
    host: 'Heroku',
    image: '/images/projects/tiresias/main.png',
    deployedLink: 'https://tiresias-predictions.herokuapp.com',
    repositoryLink: 'https://github.com/jtreeves/predictions-frontend',
    date: 'January 2021'
}

export default tiresias