const projects = {
    tiresias: {
        name: 'Tiresias',
        description: 'An app for generating regressions models',
        skills: [
            'APIs',
            'Authentication',
            'Bootstrap',
            'Chai',
            'Command Line',
            'Computer Science',
            'Design Patterns',
            'Error Handling',
            'Express', 
            'Git',
            'GitHub',
            'Heroku',
            'Information Architecture',
            'JavaScript', 
            'Mocha',
            'Mongo Atlas',
            'MongoDB',
            'Mongoose',
            'MVC Pattern',
            'Node',
            'NPM',
            'Object-Oriented Programming',
            'React',
            'User Experience Design',
            'Version Control',
            'Visual Studio Code',
            'Wireframing'
        ],
        type: 'App',
        image: '/images/projects/tiresias.png',
        deployedLink: 'https://tiresias-predictions.herokuapp.com',
        repositoryLink: 'https://github.com/jtreeves/predictions-frontend',
        date: 'January 2021'
    },

    regressionz: {
        name: 'RΣGRΣSSIONZ',
        description: 'An API to provide access to a Python library for generating regression models',
        skills: [
            'APIs',
            'Command Line',
            'Flask',
            'Git',
            'GitHub',
            'PyPi',
            'Python',
            'Postgres',
            'SQL',
            'Visual Studio Code',
            'Wireframing'
        ],
        type: 'App',
        image: '/images/projects/regressionz.png',
        deployedLink: 'https://regressionz.herokuapp.com/',
        repositoryLink: 'https://github.com/jtreeves/regressions_api',
        date: 'January 2021'
    },
    
    regressions: {
        name: 'Regressions',
        description: 'A Python library of algorithms to calculate regression models',
        skills: [
            'Algorithms',
            'Command Line',
            'Computer Science',
            'Functional Programming',
            'Git',
            'GitHub',
            'NumPy',
            'PyPi',
            'Python',
            'Version Control',
            'Visual Studio Code'
        ],
        type: 'Library',
        image: '/images/projects/regressions.png',
        deployedLink: 'https://pypi.org/project/regressions/',
        repositoryLink: 'https://github.com/jtreeves/regressions_library',
        date: 'January 2021'
    },

    kaleidoscope: {
        name: 'Kaleidoscope',
        description: 'A budget app',
        skills: [
            'Agile Development',
            'Authentication',
            'Behavior-Driven Development',
            'Chai',
            'Command Line',
            'CRUD Pattern',
            'Design Patterns',
            'Error Handling',
            'Express', 
            'Git',
            'GitHub',
            'Heroku',
            'Information Architecture',
            'JavaScript', 
            'Mocha',
            'Mongo Atlas',
            'MongoDB',
            'Mongoose',
            'MVC Pattern',
            'Node',
            'NPM',
            'Object-Oriented Programming',
            'React', 
            'Responsive Design',
            'REST Pattern',
            'Sass',
            'Test-Driven Development',
            'User Experience Design',
            'Version Control',
            'Visual Studio Code',
            'Wireframing'
        ],
        type: 'App',
        image: '/images/projects/kaleidoscope.png',
        deployedLink: 'https://kaleidoscope-budget.herokuapp.com',
        repositoryLink: 'https://github.com/jtreeves/budget-frontend',
        date: 'December 2020'
    },

    readThisNext: {
        name: 'Read This Next',
        description: 'A reading app',
        skills: [
            'APIs',
            'Authentication',
            'Bootstrap',
            'Command Line',
            'CRUD Pattern',
            'Error Handling',
            'Express', 
            'Git',
            'GitHub',
            'Heroku',
            'Information Architecture',
            'JavaScript', 
            'MVC Pattern',
            'Node',
            'NPM',
            'Object-Oriented Programming',
            'Postgres',
            'REST Pattern',
            'Sequelize',
            'SQL',
            'User Experience Design',
            'Visual Studio Code',
            'Wireframing'
        ],
        type: 'App',
        image: '/images/projects/read-this-next.png',
        deployedLink: 'https://read-this-next.herokuapp.com',
        repositoryLink: 'https://github.com/jtreeves/read-this-next',
        date: 'November 2020'
    },

    matchesAndPatches: {
        name: 'Matches and Patches',
        description: 'A game involving elements of Dominoes and Uno',
        skills: [
            'Command Line',
            'CSS',
            'Error Handling',
            'Git',
            'GitHub',
            'HTML', 
            'JavaScript',
            'Object-Oriented Programming',
            'User Experience Design',
            'Visual Studio Code',
            'Wireframing'
        ],
        type: 'App',
        image: '/images/projects/matches-and-patches.png',
        deployedLink: 'https://jtreeves.github.io',
        repositoryLink: 'https://github.com/jtreeves/matches-and-patches',
        date: 'October 2020'
    }
}

export default projects